import React from 'react'
import LayoutAdmin from '../../../components/Layout/admin'
import Head from "next/head";
import useAuth from "../../../hooks/use-auth";
import { removeUser } from '../../../api/user';
type Inputs = {
  name: string,
  id: string,
  email: string,
  phone: any,
  role: number,
}

const AdminPageUser = () => {
  const {data, error} = useAuth();
  if(error) return <div>Fail to load</div>
  if(!data) return <div>Loading...</div>
  return (
    <>
      <Head>
        <title>Admin User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full ml-14 mt-14 mb-10 md:ml-64 flex flex-col flex-auto flex-shrink-0 antialiased bg-white dark:bg-gray-700 text-black dark:text-white">
        <div className="mt-4 mx-4">
          <div className="w-full overflow-hidden rounded-lg shadow-xs">
            {/* <a
              href="product/add"
              className="float-right bg-blue-600 my-2 hover:bg-grey text-grey-darkest font-bold py-2 px-4 rounded inline-flex items-center"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 4v16m8-8H4"
                />
              </svg>
              <span>Add</span>
            </a> */}
            <div className="w-full overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                    <th className="px-4 py-3">ID</th>
                    <th className="px-4 py-3">NAME</th>
                    <th className="px-4 py-3">EMAIL</th>
                    <th className="px-4 py-3">PHONE</th>
                    <th className="px-4 py-3">ROLE</th>
                    <th className="px-4 py-3">ACTION</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                    {data.map((item :any) => {
                      return (
                  <tr key={item._id} className="bg-gray-50 dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-900 text-gray-700 dark:text-gray-400">
                    <td className="px-4 py-3">
                      <div className="flex items-center text-sm">
                        <div className="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                          <img
                            className="object-cover w-full h-full rounded-full"
                            src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3Nzg0fQ"
                            alt=""
                            loading="lazy"
                          />
                          <div
                            className="absolute inset-0 rounded-full shadow-inner"
                            aria-hidden="true"
                          />
                        </div>
                        <div>
                          {/* <p className="font-semibold">{item.id}</p> */}
                          <p className="text-xs text-gray-600 dark:text-gray-400">
                            {item._id}
                          </p>
                        </div>
                      </div>
                    </td>
                    <td className="px-4 py-3 text-sm">{item.name}</td>
                    <td className="px-4 py-3 text-xs">
                      <span className="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                        {item.email}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-sm">{item.phone}</td>
                     <td className="px-4 py-3 text-sm">{item.role}</td> 
                  <td className="px-4 py-3 text-xs">
                      <span className="px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full dark:text-red-100 dark:bg-red-700">
                      <button onClick={() => removeUser(item._id)}>Delete</button>  
                      </span>
                    </td>
                  </tr>
                      )
                      
                  
}) }
                  
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
AdminPageUser.Layout = LayoutAdmin
export default AdminPageUser