import Link from "next/link";
import React from "react";
import useCategories from "../../hooks/use-category";
import Head from "next/head";
import ProductList from "../../components/productList";

type Props = {};

const ProductPage = (props: Props) => {
  const { data, error } = useCategories();
  if (!data) return <div>Loading...</div>;
  if (error) return <div>Failed to load</div>;
  return (
    <>
      <Head>
        <title>Products | Bookstore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-40 relative mb-10 bg-gray-100">
        <div className=" w-4/6 flex mx-auto justify-around">
          <div className="w-1/6 mr-5 bg-white border border-gray-100 p-4">
            <div className="">
              <div className="flex justify-between">
                <div className="col-span-2">
                  <h1 className="text-2xl font-bold font-serif">CATEGORY</h1>
                </div>
                <div className="col-span-2">
                  <img
                    src="https://cdn-icons-png.flaticon.com/512/134/134210.png"
                    width="16px"
                  />
                </div>
              </div>
              <hr className="py-2"></hr>

              <nav className="w-3/4">
                {data.map((item: any) => (
                  <>
                    <li
                      key={item._id}
                      className="inline-block font-bold font-sans hover:text-red-700"
                    >
                      <Link href={`/category/${item._id}`}>{item.name}</Link>
                    </li>
                    <br></br>
                  </>
                ))}
              </nav>
            </div>
          </div>
          <ProductList />
        </div>
      </div>
    </>
  );
};

export default ProductPage;
