import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/Layout'
import Slide from '../components/slide'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Bookstore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Slide />
      </div>

      <main >

        <p>HomePage</p>
        <Link href="/productDetail">ProductDetail</Link>
      </main>

    </div>
  )
}
// Home.Layout = Layout;
export default Home
