import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import useSWR from 'swr'
import Layout from '../components/Layout'
import Slide from '../components/slide'
import styles from '../styles/Home.module.css'
import { formatter } from '../utils/formaterPrice'

const Home: NextPage = () => {
  const { data, error } = useSWR(`/product`);
  if(!data) return <div>Loading...</div>
  if(error) return <div>Failed</div>
  console.log(data);
  
  return (
    <div className="">
      <Head>
        <title>Bookstore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='pt-28 relative'>
        <Slide />
      </div>

      <main className=' mx-auto' >
        <div className='w-4/6 my- flex mx-auto relative'>
          <div className={styles.container}>
            <div className={styles.card}>
              <div className={styles.image}>
                <img className='w-60 relative' src="https://i.ibb.co/2KKYHmj/truck.gif" />
              </div>
              <div className={styles.content}>
                <h3 className='font-bold text-lg'>Giao hàng nhanh, miễn phí</h3>
                <p className='text-sm font-thin text-zinc-700'>Đơn hàng lớn hơn 500k hoặc đăng ký tài khoản được giao hàng miễn phí</p>
              </div>
            </div>
          </div>
          <div className={styles.container}>
            <div className={styles.card}>
              <div className={styles.image}>
                <img className='' src="https://i.ibb.co/6RkZ0Tb/diagram.gif" />
              </div>
              <div className={styles.content}>
                <h3 className='font-bold text-lg'>Trả hàng, bảo hành</h3>
                <p className='text-sm font-thin text-zinc-600'>Trả lại, đổi hàng miễn phí cho bạn trong vòng 30 ngày</p>
              </div>
            </div>
          </div>
          <div className={styles.container}>
            <div className={styles.card}>
              <div className={styles.image}>
                <img className='' src="https://i.ibb.co/Sm6S194/id-badge.gif" />
              </div>
              <div className={styles.content}>
                <h3 className='font-bold text-lg'>Thành viên</h3>
                <p className='text-sm font-thin text-zinc-600'>Ưu đãi theo từng cấp bậc hạng thành viên, sinh nhật quà tặng thành viên</p>
              </div>
            </div>
          </div>
          <div className={styles.container}>
            <div className={styles.card}>
              <div className={styles.image}>
                <img className='' src="https://i.ibb.co/825kJFm/shield.gif" />
              </div>
              <div className={styles.content}>
                <h3 className='font-bold text-lg'>Chính hãng</h3>
                <p className='text-sm font-thin text-zinc-600'>Sản phẩm chính hãng, Được nhập khẩu 100% từ hãng</p>
              </div>
            </div>
          </div>
        </div>

        {/* //? Sản phẩm mới nhất */}
        <div className='bg-gray-100 my-16 py-16 relative'>
          <div className='relative w-4/6 my-4 mx-auto flex justify-between'>
            <div >
              <div>
                <h2 className='font-bold text-5xl'>Best Seller</h2>
              </div>

            </div>
            
            <div className='flex hover:text-blue-700'>
              <div className='mx-3'>
                <Link href="">
                  <a className='text-lg '>View more</a>
                </Link>
              </div>
              <div className='mt-[5px]'>
                <svg xmlns="http://www.w3.org/2000/svg" id="Outline" viewBox="0 0 24 24" width="20" height="20"><path d="M23.12,9.91,19.25,6a1,1,0,0,0-1.42,0h0a1,1,0,0,0,0,1.41L21.39,11H1a1,1,0,0,0-1,1H0a1,1,0,0,0,1,1H21.45l-3.62,3.61a1,1,0,0,0,0,1.42h0a1,1,0,0,0,1.42,0l3.87-3.88A3,3,0,0,0,23.12,9.91Z" /></svg>
              </div>
            </div>
          </div>
          <div  className='w-4/6 flex mx-auto justify-around flex-wrap'>
          {data.map((item:any) => (
             
              <div key={item.id} className="my-8 mx-2 group relative hover:shadow-lg hover:shadow-zinc-600 hover:translate-y-[-15px] duration-500 ease-in-out transition-all bg-white rounded-md overflow-hidden">
                <div className='z-30 translate-x-[-35px] delay-100 group-hover:translate-x-[0px] ease-in-out transition-all ml-1 mt-1 absolute shadow-inner rounded-lg bg-zinc-300'>
                  <Link href={`/product/${item.slug}`}>
                    <svg xmlns="http://www.w3.org/2000/svg" className="hover:text-white hover:bg-red-500 rounded-lg h-7 w-7 text-slate-400 p-[2px]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                  </Link>
  
                </div>
  
                <div className='z-30 translate-x-[-35px] delay-150 group-hover:translate-x-[0px] ease-in-out transition-all ml-1 mt-1 absolute top-[33px] shadow-inner rounded-lg bg-zinc-300'>
                  <Link href="/product">
                    <svg xmlns="http://www.w3.org/2000/svg" className="hover:text-white hover:bg-red-500 rounded-lg h-7 w-7 text-slate-400 p-[3px]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                    </svg>
                  </Link>
  
                </div>
  
                <div className='z-30 translate-x-[-35px] delay-200 group-hover:translate-x-[0px] ease-in-out transition-all ml-1 mt-1 absolute top-[66px] shadow-inner rounded-lg bg-zinc-300'>
                  <Link href="/product">
                    <svg xmlns="http://www.w3.org/2000/svg" className="hover:text-white hover:bg-red-500 rounded-lg h-7 w-7 text-slate-400 p-[2px]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                    </svg>
                  </Link>
  
                </div>
  
                <div className="w-full min-h-80 bg-white aspect-w-1 aspect-h-1 overflow-hidden  lg:h-80 lg:aspect-none">
                 <img src={item.image} alt="" className="rounded-md px-12 pt-8 pb-4 overflow-hidden grayscale group-hover:grayscale-0  group-hover:scale-110 w-full h-full object-center object-cover ease-in-out transform transition-all lg:w-full lg:h-full" />
                </div>
  
                <div className="mt-1 ">
                  <div>
                  <h3 className="text-base my-1 text-gray-800 font-medium text-center">
                      <span aria-hidden="true" className="absolute inset-0"></span>
                     {item.name}
                    </h3>
                    
                  </div>
                  <div className='mb-2 flex justify-around'>
                    <div><del className='text-red-500'><p className="mt-1 italic text-sm text-red-500">{formatter.format(item.price)} </p></del></div>
                    <div><p className="text-base font-medium italic text-gray-500">{formatter.format(item.sale_price)}</p></div>
                  </div>
  
                </div>
              </div>
              
              
             
              
             
             
  
            
              )) }
              </div>
          
        </div>


        <div className='relative w-4/6 mx-auto mt-36 mb-60 flex justify-around'>
          <div className='my-auto w-[450px]'>
            <div className='text-left text-gray-700 text-2xl font-medium my-5'>
              <p>CREATIVE VISION</p>
            </div>
            <div className='text-left text-6xl font-bold my-5'>
              <h2>We Collect & Publish Books</h2>
            </div>
            <div className='mt-8 text-lg font-sans text-gray-700'>
              <p>Dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit sed quia.</p>
            </div>
            <div className='text-left mt-20'>
              <Link className='border-2 px-9  ease-in-out transition-all hover:bg-yellow-700 py-4 bg-yellow-500 text-slate-50' href="">About Us</Link>
            </div>
          </div>
          {/* left */}

          <div className='w-[600px]'>
            <div className='absolute left-[60%] bottom-[-30%] z-30'>
              <Link href="">
                <img className='hover:shadow-lg hover:shadow-black rounded-md z-10 grayscale hover:grayscale-0 hover:translate-y-[-30px] ease-in-out  transition-all ' src="https://writer.ancorathemes.com/wp-content/uploads/2021/12/image-2.jpg" alt="" width="400px" />
              </Link>
            </div>
            <div >
              <Link href="">
                <img className='shadow-lg hover:shadow-black rounded-md hover:translate-y-[-30px] grayscale hover:grayscale-0 ease-in-out transition-all' src="https://writer.ancorathemes.com/wp-content/uploads/2022/01/post-image-10.jpg" alt="" width="410px" />
              </Link>
            </div>
          </div>
          {/* right */}
        </div>

        {/* //? Sản phẩm mới nhất */}
        <div className='bg-gray-200 my-16 py-16 relative'>
          <div className='w-4/6 my-4 mx-auto flex justify-between'>
            <div >
              <div>
                <h2 className='font-bold text-5xl'>New Products</h2>
              </div>

            </div>
            <div className='flex hover:text-blue-700'>
              <div className='mx-3'>
                <Link href="">
                  <a className='text-lg '>View more</a>
                </Link>
              </div>
              <div className='mt-[5px]'>
                <svg xmlns="http://www.w3.org/2000/svg" id="Outline" viewBox="0 0 24 24" width="20" height="20"><path d="M23.12,9.91,19.25,6a1,1,0,0,0-1.42,0h0a1,1,0,0,0,0,1.41L21.39,11H1a1,1,0,0,0-1,1H0a1,1,0,0,0,1,1H21.45l-3.62,3.61a1,1,0,0,0,0,1.42h0a1,1,0,0,0,1.42,0l3.87-3.88A3,3,0,0,0,23.12,9.91Z" /></svg>
              </div>
            </div>
          </div>
          
          <div className='w-[1260px] flex mx-auto justify-around flex-wrap'>
          {data.map((item:any) => (
             
             <div key={item.id} className="my-8 mx-2 group relative hover:shadow-lg hover:shadow-zinc-600 hover:translate-y-[-15px] duration-500 ease-in-out transition-all bg-white rounded-md overflow-hidden">
               <div className='z-30 translate-x-[-35px] delay-100 group-hover:translate-x-[0px] ease-in-out transition-all ml-1 mt-1 absolute shadow-inner rounded-lg bg-zinc-300'>
                 <Link href={`/product/${item.slug}`}>
                   <svg xmlns="http://www.w3.org/2000/svg" className="hover:text-white hover:bg-red-500 rounded-lg h-7 w-7 text-slate-400 p-[2px]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                     <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                     <path strokeLinecap="round" strokeLinejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                   </svg>
                 </Link>
 
               </div>
 
               <div className='z-30 translate-x-[-35px] delay-150 group-hover:translate-x-[0px] ease-in-out transition-all ml-1 mt-1 absolute top-[33px] shadow-inner rounded-lg bg-zinc-300'>
                 <Link href="/product">
                   <svg xmlns="http://www.w3.org/2000/svg" className="hover:text-white hover:bg-red-500 rounded-lg h-7 w-7 text-slate-400 p-[3px]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                     <path strokeLinecap="round" strokeLinejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                   </svg>
                 </Link>
 
               </div>
 
               <div className='z-30 translate-x-[-35px] delay-200 group-hover:translate-x-[0px] ease-in-out transition-all ml-1 mt-1 absolute top-[66px] shadow-inner rounded-lg bg-zinc-300'>
                 <Link href="/product">
                   <svg xmlns="http://www.w3.org/2000/svg" className="hover:text-white hover:bg-red-500 rounded-lg h-7 w-7 text-slate-400 p-[2px]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                     <path strokeLinecap="round" strokeLinejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                   </svg>
                 </Link>
 
               </div>
 
               <div className="w-full min-h-80 bg-white aspect-w-1 aspect-h-1 overflow-hidden  lg:h-80 lg:aspect-none">
                <img src={item.image} alt="" className="rounded-md px-12 pt-8 pb-4 overflow-hidden grayscale group-hover:grayscale-0  group-hover:scale-110 w-full h-full object-center object-cover ease-in-out transform transition-all lg:w-full lg:h-full" />
               </div>
 
               <div className="mt-1 ">
                 <div>
                 <h3 className="text-base my-1 text-gray-800 font-medium text-center">
                     <span aria-hidden="true" className="absolute inset-0"></span>
                    {item.name}
                   </h3>
                   
                 </div>
                 <div className='mb-2 flex justify-around'>
                   <div><del className='text-red-500'><p className="mt-1 italic text-sm text-red-500">{formatter.format(item.price)} </p></del></div>
                   <div><p className="text-base font-medium italic text-gray-500">{formatter.format(item.sale_price)}</p></div>
                 </div>
 
               </div>
             </div>
             
             
            
             
            
            
 
           
             )) }

          </div>
        </div>

        <div className='w-4/6 my-14 mx-auto relative mt-28'>
                <div>
                    <p className='font-medium text-xl'>WHAT NEW</p>
                    <h2 className='mt-8 mb-16 font-serif text-7xl'>Blog Updates</h2>
                    <div className='flex justify-center'>
                        <div className='ml-[70px]'>
                            <div> <img src="https://writer.ancorathemes.com/wp-content/uploads/2022/01/post-image-7.jpg" width="600px" alt="" /></div>
                            <div className='flex mt-7'>
                                <div className='w-[120px]'>
                                    <p className='font-medium text-5xl'>13</p>
                                    <p className='font-medium'>MAR</p>
                                </div>
                                <div className='w-[480px] text-left'>
                                    <h4 className='font-serif text-black text-4xl'>What do you need for a calm and relaxing vacation ?</h4>
                                    <p className='mt-[10px] font-sans text-zinc-500'>Adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
                                </div>
                            </div>

                        </div>
                        {/* left */}
                        <div className='ml-8'>
                            <div className='flex mb-7'>
                                <div className='mr-8'>
                                    <img src="https://writer.ancorathemes.com/wp-content/uploads/2022/01/post-image-7.jpg" width="236px" alt="" />
                                </div>
                                <div className='my-auto '>
                                    <div className='flex'>
                                        <h6 className='font-medium text-2xl mr-4'>UPDATES</h6>
                                        <p className='text-zinc-500 mt-[5px] font-sans' >Mar 13.2020</p>
                                    </div>
                                    <div className='w-[400px] text-left'>
                                        <h4 className='font-sans text-3xl'>Start your day properly with the hottest novelties</h4>
                                    </div>
                                </div>
                            </div>

                            <div className='flex mb-7'>
                                <div className='mr-8'>
                                    <img src="https://writer.ancorathemes.com/wp-content/uploads/2022/01/post-image-7.jpg" width="236px" alt="" />
                                </div>
                                <div className='my-auto '>
                                    <div className='flex'>
                                        <h6 className='font-medium text-2xl mr-4'>UPDATES</h6>
                                        <p className='text-zinc-500 mt-[5px] font-sans' >Mar 13.2020</p>
                                    </div>
                                    <div className='w-[400px] text-left'>
                                        <h4 className='font-sans text-3xl'>Start your day properly with the hottest novelties</h4>
                                    </div>
                                </div>
                            </div>

                            <div className='flex mb-7'>
                                <div className='mr-8'>
                                    <img src="https://writer.ancorathemes.com/wp-content/uploads/2022/01/post-image-7.jpg" width="236px" alt="" />
                                </div>
                                <div className='my-auto '>
                                    <div className='flex'>
                                        <h6 className='font-medium text-2xl mr-4'>UPDATES</h6>
                                        <p className='text-zinc-500 mt-[5px] font-sans' >Mar 13.2020</p>
                                    </div>
                                    <div className='w-[400px] text-left'>
                                        <h4 className='font-sans text-3xl'>Start your day properly with the hottest novelties</h4>
                                    </div>
                                </div>
                            </div>
                            <div className='flex mb-7'>
                                <div className='mr-8'>
                                    <img src="https://writer.ancorathemes.com/wp-content/uploads/2022/01/post-image-7.jpg" width="236px" alt="" />
                                </div>
                                <div className='my-auto '>
                                    <div className='flex'>
                                        <h6 className='font-medium text-2xl mr-4'>UPDATES</h6>
                                        <p className='text-zinc-500 mt-[5px] font-sans' >Mar 13.2020</p>
                                    </div>
                                    <div className='w-[400px] text-left'>
                                        <h4 className='font-sans text-3xl'>Start your day properly with the hottest novelties</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* right */}
                    </div>
                </div>
                {/* title */}
            </div>

        <div className="bg-gray-200 my-10 w-full flex items-center justify-center p-12 py-6">
          <div className="w-4/6 mx-auto px-5 py-16">
            <div className="grid gap-5 md:grid-cols-2 md:gap-10 lg:gap-20">
              <div className="flex justify-center md:justify-end">
                <img className="w-full max-w-sm" src="https://ouch-cdn2.icons8.com/sKnF2PmYhkmP28DzIm6KqWSknT03UVWjg3FLlGYIOp4/rs:fit:684:456/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9zdmcvOTI3/L2U4OWQ2NmZiLTg0/NzEtNDc3NS1hNTA0/LTMwNWRiYmJkNzg0/MC5zdmc.png" alt="Marketing newsletter via computer Illustration in PNG, SVG" />
              </div>
              <div className="flex items-center">
                <div className="mx-auto md:mx-0">
                  <h3 className="text-4xl font-bold text-black">Subscribe</h3>
                  <p className="mt-2 max-w-[20rem] text-lg text-black/80">Join our weekly digest. You will also receive some of our best posts today.</p>
                  <form action="" className="mt-4 flex flex-col">
                    <input type="email" name="email" id="email" placeholder="Enter your email" className="w-full rounded border border-black/50 bg-transparent px-3 py-2 text-black placeholder:text-black/50 md:max-w-[18rem]" />
                    <button type="submit" className="hover:bg-blue-700 duration-200 ease-in-out hover:text-white mt-4 w-full max-w-[14rem] rounded bg-black/30 px-14 py-2 text-center text-black">Subscribe</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </main >

    </div >
  )
}
// Home.Layout = Layout;
export default Home
