import React, { useEffect } from 'react'
import {SubmitHandler, useForm} from 'react-hook-form'
import toastr from 'toastr'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { userType } from "../../models/user"
import { getUser, listUser } from '../../api/auth';
import useAuth from '../../hooks/use-auth'
import Layout from '../../components/Layout'


const EditName = () => {
  const router = useRouter()
  const {update} = useAuth()
  const { _id} = router.query
  const {register, handleSubmit, formState: {errors}, reset} = useForm<userType>()
  useEffect(() => {
    (async() => {
      const user = await getUser(_id)
      reset(user)
    })()
  },[])
  

  const onSubmit: SubmitHandler<userType> = async (user) => {
    const data = await update(user)
  toastr.success("Sửa thông thành công")
    setTimeout(() => {
      
    router.push("/profile")

    },2000)
  }
  return (
    <div>

      <Head>
        <title>Edit Profile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="toastr.css" rel="stylesheet"/> */}
      </Head>
    <div className="pt-80">
      <div className="mt-4 mx-4">
        <div className="max-w-5xl mx-auto">
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className="relative z-0 mb-6 w-full group">
                <input
                  type="name"
                  name=""
                  className="block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  required
                />
                <label
                  htmlFor=""
                  className="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Name
                </label>
              </div>
              <div className="relative z-0 mb-6 w-full group">
                <input
                  type="email"
                  name=""
                  id=""
                  className="block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  required
                />
                <label
                  htmlFor=""
                  className="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Email
                </label>
              </div>
              <div className="relative z-0 mb-6 w-full group">
                <input
                  type="number"
                  name=""
                  className="block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  required
                />
                <label
                  htmlFor=""
                  className="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
                >
                  Phone
                </label>
              </div>
              <button
                type="submit"
                className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
              >
                Submit
              </button>
          </form>
        </div>
      </div>
    </div>
    {/* <script src="toastr.js"></script> */}
    </div>
  )
}
EditName.Layout = Layout

export default EditName 